apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: graphql
      port: 8080
      protocol: TCP
    - name: authorization
      port: 8081
      protocol: TCP
    - name: rest
      port: 8082
      protocol: TCP
    - name: health
      port: 8084
      protocol: TCP
    - name: metrics
      port: 8085
      protocol: TCP
    - name: cassandra
      protocol: TCP
      port: 9042
  selector: {{- include "k8ssandra-common.selectorLabels" . | nindent 4 }}
