{{- $password := (include "k8ssandra-common.password" .) }}
{{- $secretName := (print (include "k8ssandra.clusterName" . ) "-reaper-jmx") }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}

{{- if .Values.reaper.enabled }}

{{- if $secret }}
{{- $password = index $secret.data "password" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.reaper.jmx.username }}
  username: {{ .Values.reaper.jmx.username | b64enc | quote }}
  {{- else }}
  username: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.reaper.jmx.password }}
  password: {{ .Values.reaper.jmx.password | b64enc | quote }}
  {{- else }}
  password: {{ $password }}
  {{- end }}
{{- end }}
