# -- Name of the CassandraRestore custom resource
name: restore


backup:
  # -- Name of the CassandraBackup custom resource to be restored from
  name: backup

cassandraDatacenter:
  # -- Name of the CassandraDatacenter where the CassandraBackup will be
  # restored
  name: dc1

# -- In-place restore will restore the backup to the source cluster.
inPlace: true

# -- When true will shutdown the entire Cassandra cluster. The underlying
# StatefulSets are scaled down to zero. Persistent volumes remain intact. If the
# backup includes schema changes like dropping a table, then must be set to
# true; otherwise, the changes will be lost via gossip from nodes that have
# not yet been restored. It is recommended in general to shutdown the cluster
# prior to a restore to avoid data inconsistencies and/or data loss that could
# happen with clients writing to the cluster while the restore operation is in
# progress.
#
# When set the cluster is shutdown, and the restore operations happen in
# parallel across all Cassandra pods. If `shutdown` is `false` the restore
# operation is done via a rolling restart where the restore operation runs on
# each pod serially.
shutdown: true
